# Publicly accessible address of this node
advertise_addr: "your-public-ip:10000"

# Signature block for license verification
# Refer to ./doc/License_attachment.md for instructions on generating license signatures
signatures:
  - license_id: # Unique license identifier
    license_owner_pubkey: # Public key of the license owner
    provider_pubkey: # Public key of the service provider
    license_proof_sig: # Proof signature of the license
    delegation_sig: # Signature for delegation
    delegation_confirm_sig: # Confirmation signature from the provider
    timestamp: # Timestamp of the <delegation_sig> creation

# This section, especially the cert field, is optional. Use it only if you have proxies.
#
# proxies:
#   - socket_address: "ipv4_address:port"
#     cert: |
#       -----BEGIN CERTIFICATE-----
#       MIIDdzCCAl+gAwIBAgIEbZUg8DANBgkqhkiG9w0BAQsFADBvMQswCQYDVQQGEwJV
#       MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtv9bXZ57KzE3...
#       uFJgx1A/kErMItvEr3vW9YKtRfA1LP5zZb8fE6TwE9fY2kW2E=
#       -----END CERTIFICATE-----

# Enable auto-update and automatic restart of the Acki Nacki Node Docker image
auto_update: true

# DO NOT MODIFY the following parameters
cluster_id: "acki-nacki-igniter"
listen_addr: "0.0.0.0:10000" # Address to accept P2P connections
api_addr: "0.0.0.0:10001" # Local API server address
interval: 1000 # Heartbeat interval in milliseconds

